### ISSUE TITLE
Error occurred during initialization of boot layer

### ISSUE THREAD

**Issue by hungthuanmk** [openjfx/javafx-maven-plugin#24]
Hi guys, i am stuck in making JavaFX program with Hadoop FS. I use Maven, JDK 11 and JavaFX 12. I think it has trouble when maven tries to add hadoop module to parameter behind javafx:run command.
This is my pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.vn.somegroup</groupId>
    <artifactId>DemoHadoopFiles</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>12.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>12.0.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-client -->
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-client</artifactId>
            <version>3.2.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-common -->
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>3.2.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.2</version>
                <configuration>
                    <mainClass>HelloFX</mainClass>
                    <source>11</source>
                    <target>11</target>
                    <release>11</release>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```
And this is console log when run with command "mvn clean javafx:run -X"
```
"C:\Program Files\Java\jdk-11.0.1\bin\java.exe" -Dmaven.multiModuleProjectDirectory=D:\IT\IdeaProjects\DemoHadoopFiles "-Dmaven.home=D:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\plugins\maven\lib\maven3" "-Dclassworlds.conf=D:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\plugins\maven\lib\maven3\bin\m2.conf" "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\lib\idea_rt.jar=50230:D:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\bin" -Dfile.encoding=UTF-8 -classpath "D:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version2019.1.1 clean javafx:run -X
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T23:41:47+07:00)
Maven home: D:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5\plugins\maven\lib\maven3
Java version: 11.0.1, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk-11.0.1
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
[INFO] Scanning for projects...
[DEBUG] Tasks:   [clean, javafx:run]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building DemoHadoopFiles 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <directory default-value="${project.build.directory}"/>
  <excludeDefaultDirectories default-value="false">${clean.excludeDefaultDirectories}</excludeDefaultDirectories>
  <failOnError default-value="true">${maven.clean.failOnError}</failOnError>
  <followSymLinks default-value="false">${clean.followSymLinks}</followSymLinks>
  <outputDirectory default-value="${project.build.outputDirectory}"/>
  <reportDirectory default-value="${project.reporting.outputDirectory}"/>
  <retryOnError default-value="true">${maven.clean.retryOnError}</retryOnError>
  <skip default-value="false">${clean.skip}</skip>
  <testOutputDirectory default-value="${project.build.testOutputDirectory}"/>
  <verbose>${clean.verbose}</verbose>
</configuration>
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.openjfx:javafx-maven-plugin:0.0.2:run (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <async default-value="false">${javafx.async}</async>
  <asyncDestroyOnShutdown default-value="true">${javafx.asyncDestroyOnShutdown}</asyncDestroyOnShutdown>
  <basedir default-value="${basedir}"/>
  <builddir default-value="${project.build.directory}"/>
  <commandlineArgs>${javafx.args}</commandlineArgs>
  <compilePath default-value="${project.compileClasspathElements}"/>
  <executable default-value="java">${javafx.executable}</executable>
  <mainClass>HelloFX</mainClass>
  <outputFile>${javafx.outputFile}</outputFile>
  <project default-value="${project}"/>
  <release default-value="11">11</release>
  <session default-value="${session}"/>
  <skip default-value="false">${javafx.skip}</skip>
  <source default-value="11">11</source>
  <target default-value="11">11</target>
  <workingDirectory>${javafx.workingDirectory}</workingDirectory>
</configuration>
[DEBUG] =======================================================================
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=2, ConflictMarker.markTime=1, ConflictMarker.nodeCount=577, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=116, ConflictIdSorter.conflictIdCycleCount=4, ConflictResolver.totalTime=8, ConflictResolver.conflictItemCount=217, DefaultDependencyCollector.collectTime=536, DefaultDependencyCollector.transformTime=14}
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ DemoHadoopFiles ---
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-clean-plugin:2.5:clean' with basic configurator -->
[DEBUG]   (f) directory = D:\IT\IdeaProjects\DemoHadoopFiles\target
[DEBUG]   (f) excludeDefaultDirectories = false
[DEBUG]   (f) failOnError = true
[DEBUG]   (f) followSymLinks = false
[DEBUG]   (f) outputDirectory = D:\IT\IdeaProjects\DemoHadoopFiles\target\classes
[DEBUG]   (f) reportDirectory = D:\IT\IdeaProjects\DemoHadoopFiles\target\site
[DEBUG]   (f) retryOnError = true
[DEBUG]   (f) skip = false
[DEBUG]   (f) testOutputDirectory = D:\IT\IdeaProjects\DemoHadoopFiles\target\test-classes
[DEBUG] -- end configuration --
[INFO] Deleting D:\IT\IdeaProjects\DemoHadoopFiles\target
[INFO] Deleting file D:\IT\IdeaProjects\DemoHadoopFiles\target\maven-status\maven-compiler-plugin\compile\null\inputFiles.lst
[INFO] Deleting file D:\IT\IdeaProjects\DemoHadoopFiles\target\maven-status\maven-compiler-plugin\compile\null\createdFiles.lst
[INFO] Deleting directory D:\IT\IdeaProjects\DemoHadoopFiles\target\maven-status\maven-compiler-plugin\compile\null
[INFO] Deleting directory D:\IT\IdeaProjects\DemoHadoopFiles\target\maven-status\maven-compiler-plugin\compile
[INFO] Deleting directory D:\IT\IdeaProjects\DemoHadoopFiles\target\maven-status\maven-compiler-plugin
[INFO] Deleting directory D:\IT\IdeaProjects\DemoHadoopFiles\target\maven-status
[INFO] Deleting directory D:\IT\IdeaProjects\DemoHadoopFiles\target\generated-sources\annotations
[INFO] Deleting directory D:\IT\IdeaProjects\DemoHadoopFiles\target\generated-sources
[INFO] Deleting file D:\IT\IdeaProjects\DemoHadoopFiles\target\classes\sample.fxml
[INFO] Deleting file D:\IT\IdeaProjects\DemoHadoopFiles\target\classes\HelloFX.class
[INFO] Deleting file D:\IT\IdeaProjects\DemoHadoopFiles\target\classes\FSManager.class
[INFO] Deleting file D:\IT\IdeaProjects\DemoHadoopFiles\target\classes\Controller.class
[INFO] Deleting directory D:\IT\IdeaProjects\DemoHadoopFiles\target\classes
[INFO] Deleting directory D:\IT\IdeaProjects\DemoHadoopFiles\target
[DEBUG] Skipping non-existing directory D:\IT\IdeaProjects\DemoHadoopFiles\target\classes
[DEBUG] Skipping non-existing directory D:\IT\IdeaProjects\DemoHadoopFiles\target\test-classes
[DEBUG] Skipping non-existing directory D:\IT\IdeaProjects\DemoHadoopFiles\target\site
[INFO] 
[INFO] --- javafx-maven-plugin:0.0.2:run (default-cli) @ DemoHadoopFiles ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=160, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=59, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2, ConflictResolver.conflictItemCount=102, DefaultDependencyCollector.collectTime=206, DefaultDependencyCollector.transformTime=2}
[DEBUG]   (f) executable = java
[DEBUG]   (f) mainClass = HelloFX
[DEBUG]   (f) release = 11
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@22752544
[DEBUG]   (f) skip = false
[DEBUG]   (f) source = 11
[DEBUG]   (f) target = 11
[DEBUG] -- end configuration --
[DEBUG] Output directory was empty, compiling...
[DEBUG] Running executeMojo for Plugin [org.apache.maven.plugins:maven-resources-plugin]
[DEBUG] Attempting to load plugin Plugin [org.apache.maven.plugins:maven-resources-plugin] using pluginManager org.apache.maven.plugin.DefaultBuildPluginManager@51d719bc and repositories [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=77, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=26, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=0, ConflictResolver.conflictItemCount=74, DefaultDependencyCollector.collectTime=55, DefaultDependencyCollector.transformTime=1}
[DEBUG]   (f) supportMultiLineFiltering = false
[DEBUG]   (f) useBuildFilters = true
[DEBUG]   (s) useDefaultDelimiters = true
[DEBUG] -- end configuration --
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[DEBUG] resource with targetPath null
directory D:\IT\IdeaProjects\DemoHadoopFiles\src\main\resources
excludes []
includes []
[DEBUG] ignoreDelta true
[INFO] Copying 1 resource
[DEBUG] file sample.fxml has a filtered file extension
[DEBUG] copy D:\IT\IdeaProjects\DemoHadoopFiles\src\main\resources\sample.fxml to D:\IT\IdeaProjects\DemoHadoopFiles\target\classes\sample.fxml
[DEBUG] no use filter components
[DEBUG] Running executeMojo for Plugin [org.apache.maven.plugins:maven-compiler-plugin]
[DEBUG] Attempting to load plugin Plugin [org.apache.maven.plugins:maven-compiler-plugin] using pluginManager org.apache.maven.plugin.DefaultBuildPluginManager@51d719bc and repositories [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=118, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=45, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=1, ConflictResolver.conflictItemCount=72, DefaultDependencyCollector.collectTime=100, DefaultDependencyCollector.transformTime=1}
Error occurred during initialization of boot layer
**java.lang.module.ResolutionException: Modules hadoop.yarn.common and hadoop.yarn.client export package org.apache.hadoop.yarn.client.api to module paranamer
[ERROR] Command execution failed.**
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:447)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:409)
	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:97)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.947 s
[INFO] Finished at: 2019-06-06T12:05:46+07:00
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:447)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:409)
	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:97)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[INFO] Final Memory: 19M/64M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.2:run (default-cli) on project DemoHadoopFiles: Error: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.2:run (default-cli) on project DemoHadoopFiles: Error
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error
	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:114)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:108)
	... 23 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:447)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:409)
	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:97)
	... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1
```
Many thanks!

**Comment by matthias24** [comment]
Hello together,

it seems I have run into the same issue. I import zwo or more Maven-Dependencies with the same package inside, and the same error occures. This would be normal, if the dependencies would be modules. But this is not the case with any of my dependencies or the project i want to run. But the console log hints at the root of the problem. It seem, the javafx-maven-plugin sees all Maven-Dependencies as modules, what is somewhat odd. What could be the solution or is it a bug?

Here is the colsole log:
`[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< de.bayern.lvg:testMavenFx >----------------------
[INFO] Building testMavenFx 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.postgresql:postgresql:jar:42.0.0.jre7 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:9.4.1209.jre6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:9.4.1209.jre7 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:9.4.1210.jre7 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.1.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.1.3.jre6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.2.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.2.0.jre6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.2.0.jre7 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.2.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.2.1.jre6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.2.1.jre7 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.2.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.2.2.jre6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.2.2.jre7 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.postgresql:postgresql:jar:42.2.2.redhat-2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ testMavenFx ---
[INFO] Deleting D:\daten\projekte\testMavenFx\target
[INFO] 
[INFO] --- javafx-maven-plugin:0.0.2:run (default-cli) @ testMavenFx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\daten\projekte\testMavenFx\src\main\resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to D:\daten\projekte\testMavenFx\target\classes
[WARNING] Can't extract module name from jdom-1.1.jar: JDOMAbout$Author.class found in top-level directory (unnamed package not allowed in module)
[WARNING] Can't extract module name from jboss-transaction-api_1.2_spec-1.0.1.Final.jar: jboss.transaction.api.1.2.spec: Invalid module name: '1' is not a Java identifier
[WARNING] Can't extract module name from gt-api-18.0.0.1-gt-main.jar: Provider class org.geotools.data.gml.GMLDataSourceFactory not in module
[WARNING] Can't extract module name from jsr-275-0.9.3.jar: jsr.275: Invalid module name: '275' is not a Java identifier
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules lvg.geo.io and lvg.geo2 export package de.bayern.lvg.geo.ve to module javafx.controlsEmpty
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:447)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:409)
	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:97)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:447)
	at org.openjfx.JavaFXBaseMojo.executeCommandLine(JavaFXBaseMojo.java:409)
	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:97)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.357 s
[INFO] Finished at: 2019-06-17T16:50:58+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.2:run (default-cli) on project testMavenFx: Error: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

The important hint is:

> `[WARNING] Can't extract module name from jdom-1.1.jar: JDOMAbout$Author.class found in top-level directory (unnamed package not allowed in module)`

Many thanks, too :-)

**Comment by jperedadnr** [comment]
@matthias24  This is the same issue as posted here: #17, and there is already a PR to fix it #18. You can test it already if you build and install the plugin from [here](https://github.com/atdixon/javafx-maven-plugin/tree/cp-includes-path-exceptions).

**Comment by DfM7** [comment]
@jperedadnr 
I guess the issue isn't fixed yet?

I've tried latest 0.0.3-SNAPSHOT and I got

> 
> [INFO] --- javafx-maven-plugin:0.0.3-SNAPSHOT:run (default-cli) @ server ---
> Error occurred during initialization of boot layer
> java.lang.module.ResolutionException: Modules lucene.core and lucene.misc export package org.apache.lucene.store to module javassist
> [ERROR] Command execution failed.

**Comment by jperedadnr** [comment]
@DfM7 that's not related to the issue at hand that has been fixed (having classes at the top-level directory, i.e. without a package name). Yours looks like a split package problem.

**Comment by DfM7** [comment]
@jperedadnr 
I have a non-modular project (no module-info.java files).
So, as I understand, the packages listed in the error should be a part on an unnamed module and no errors should be thrown.

**Comment by jperedadnr** [comment]
@DfM7 Thanks, could you open a new issue, and link that SO question?

**Comment by DfM7** [comment]
@jperedadnr 
Sorry for the delay.
As I see, you've already done this. So I'll reference the issue here for completeness.
Here it is: #34.

**Comment by jperedadnr** [comment]
@DfM7 Thanks, no problem. I've already submitted a PR to fix it.

**Comment by DfM7** [comment]
@hungthuanmk 
You can try #35, it may fix your issue as it has fixed mine.

**Comment by phydesmith** [comment]
Hello,

I added a dependency for derby and my program is now bombing out at run time. I am new to maven and programming in general, so this might be an error on my part, but I am getting a similar error.

I have configured derby following the directions outlined in the documentation. I have also been able to get a sample application to run by doing something like this after cleaning and compiling with maven:

javac -classpath $CLASSPATH:target/sample.jar io.javasmithy.App


However, since I am using the javafx:run goal it is not working. I noticed there are some options I can add, but none of those seem to work.
I run:

mvn clean compile javafx:run

I have attached the output of the above command and my pom. 


[weather-app-error.txt](https://github.com/openjfx/javafx-maven-plugin/files/3432499/weather-app-error.txt)

[pom.txt](https://github.com/openjfx/javafx-maven-plugin/files/3432498/pom.txt)

**Comment by phydesmith** [comment]
I was able to get my program to work using a similar command as above, and adding the correct javafx modules using the --module-path and --add-modules args. My issue was i had incorrectly set the classpath variables required for derby. 

However, I still am unable to get the javafx:run goal working at this point. I will try to read the documentation more carefully and see if there are settings I have missed.

**Comment by jperedadnr** [comment]
@phydesmith Make sure you use the latest plugin version: 0.0.3, we have fixed a possible related issue.

**Comment by matthias24** [comment]
@jperedadnr Thank you very much, Version 0.0.3 works for me. So for me this issue is resolved.

**Comment by jperedadnr** [comment]
Ok, I'm going to close this issue (actually an aggregation of different issues). 

If any of these issues is still unresolved, please file a new issue for it.
